version: '3.7'

services:
    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
            MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodbdata:/data/db
volumes:
    mongodbdata:
        driver: local